# Generated by Django 3.0.5 on 2020-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-rating',)},
        ),
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.BigIntegerField(blank=True, default=1000000),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='producer',
            field=models.CharField(blank=True, max_length=124),
        ),
    ]
