# Generated by Django 3.0.5 on 2020-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200424_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='films', to='main.Category'),
        ),
    ]
