# Generated by Django 3.0.5 on 2020-06-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='number_of_comments',
            field=models.IntegerField(default=100),
        ),
    ]
